[package]
name = "quake-files"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
image = "*"
byteorder = "*"
walkdir = "*"

[dependencies.clippy]
optional = true
version = "*"

[features]
nightly = ["clippy"]